const places = [
  {id:"moraine",name:"Breiðármörk",coordinates:[-16.3500,64.1050],source:"https://www.vatnajokulsthjodgardur.is/en/melting-glaciers/glaciology"},
  {id:"sandur",name:"Skeiðarársandur",coordinates:[-17.1823,63.960833],source:"https://whc.unesco.org/en/list/1604/"},
  {id:"lagoon",name:"Jökulsárlón",coordinates:[-16.2306,64.0784],source:"https://www.vatnajokulsthjodgardur.is/en/areas/jokulsarlon"}
];

const copy={
  en:{journal:"Journal",eyebrow:"Field expedition 001 · Iceland",title:"Read the land.<br>Follow the water.",intro:"A glacier has written a story across Iceland's south coast. Follow three verified traces and reveal how ice, water, and fire shape the road to the sea.",level:"● Curious beginner",time:"12–15 minutes",region:"South Vatnajökull",hint:"Select the illuminated marker to investigate",progress:"Expedition progress",clue:"Clue",field:"Field note",manifesto:"The world is not a checklist.",manifestoTitle:"Every landscape leaves evidence.<br>Your task is to notice.",made:"Discovery made",knowledge:"Geology knowledge",record:"Record and continue",explorerJournal:"Explorer's journal",notes:"Iceland field notes",empty:"Your first discovery is still waiting in the landscape.",investigate:"Investigate marker {n}",complete:"Expedition complete",viewSource:"View verified source ↗",welcomeEyebrow:"A world of evidence and wonder",welcomeCopy:"Every mountain has a story. Every river remembers. Begin an explorer's journal shaped by what makes you curious.",begin:"Begin your journey",continueProfile:"Continue as explorer",profileEyebrow:"Your explorer profile",profileTitle:"What should your journal call you?",explorerName:"Explorer name",guideLanguage:"Guide language",chooseExpedition:"Choose an expedition",firstExpedition:"Your first expedition",whereFirst:"Where will you look first?",available:"Available now",fieldExpedition:"Field expedition 001",fireIce:"Iceland · A story of fire and ice",threeDiscoveries:"3 discoveries",comingSoon:"Coming soon",futureExpedition:"Future expedition",patagonia:"Patagonia · Where continents end",preparing:"Preparing your expedition",
    clues:[["The ridge that records an edge","Begin on Breiðármörk, in the foreland of a retreating outlet glacier. Look for ridges of debris beside the ice. What moving force deposited them?","Debris carried by a glacier is deposited at its sides and margin as moraines."],["A plain written by floods","Travel west to the enormous dark plain between glacier and ocean. Its rivers divide, migrate, and reunite across sediment carried from Vatnajökull.","Repeated glacial floods and meltwater build the broad plains Icelanders call sandur."],["Where ice becomes ocean","Return east to a lake divided from the Atlantic by a narrow strip of land. Here, pieces of Breiðamerkurjökull begin a visible journey toward the sea.","Glacial lakes form in deep basins exposed as outlet glaciers retreat."]],
    discoveries:[["A landscape of moraines","Breiðármörk preserves ridges and sediments left as glaciers advanced and retreated. Moraines make former ice margins readable in today's terrain."],["Skeiðarársandur outwash plain","Meltwater and sudden jökulhlaup floods spread volcanic and glacial sediment toward the ocean, creating a vast, continually changing sandur plain."],["Jökulsárlón glacial lagoon","Jökulsárlón occupies a deep trough carved by Breiðamerkurjökull. As the glacier retreats and calves, icebergs cross the lagoon toward the Atlantic."]]},
  fr:{journal:"Carnet",eyebrow:"Expédition 001 · Islande",title:"Lisez la terre.<br>Suivez l’eau.",intro:"Un glacier a écrit une histoire sur la côte sud de l’Islande. Suivez trois traces vérifiées et découvrez comment la glace, l’eau et le feu façonnent le chemin vers la mer.",level:"● Explorateur débutant",time:"12–15 minutes",region:"Sud du Vatnajökull",hint:"Sélectionnez le repère illuminé",progress:"Progression de l’expédition",clue:"Indice",field:"Note de terrain",manifesto:"Le monde n’est pas une liste.",manifestoTitle:"Chaque paysage laisse des indices.<br>À vous de les remarquer.",made:"Découverte",knowledge:"Connaissances en géologie",record:"Noter et continuer",explorerJournal:"Carnet de l’explorateur",notes:"Notes de terrain · Islande",empty:"Votre première découverte vous attend encore dans le paysage.",investigate:"Examiner le repère {n}",complete:"Expédition terminée",viewSource:"Voir la source vérifiée ↗",welcomeEyebrow:"Un monde de preuves et d’émerveillement",welcomeCopy:"Chaque montagne a une histoire. Chaque rivière se souvient. Commencez un carnet d’exploration façonné par votre curiosité.",begin:"Commencer le voyage",continueProfile:"Continuer comme explorateur",profileEyebrow:"Votre profil d’explorateur",profileTitle:"Quel nom votre carnet doit-il utiliser ?",explorerName:"Nom de l’explorateur",guideLanguage:"Langue du guide",chooseExpedition:"Choisir une expédition",firstExpedition:"Votre première expédition",whereFirst:"Où regarderez-vous en premier ?",available:"Disponible",fieldExpedition:"Expédition 001",fireIce:"Islande · Une histoire de feu et de glace",threeDiscoveries:"3 découvertes",comingSoon:"Bientôt",futureExpedition:"Expédition future",patagonia:"Patagonie · Là où finissent les continents",preparing:"Préparation de votre expédition",
    clues:[["La crête qui conserve une limite","Commencez à Breiðármörk, devant un glacier en retrait. Cherchez les crêtes de débris près de la glace. Quelle force les a déposées ?","Les débris transportés par un glacier se déposent sur ses côtés et à sa marge sous forme de moraines."],["Une plaine écrite par les crues","Partez vers l’ouest jusqu’à l’immense plaine sombre entre glacier et océan. Ses rivières se divisent et se rejoignent sur les sédiments du Vatnajökull.","Les crues glaciaires et l’eau de fonte construisent les vastes plaines appelées sandur."],["Là où la glace devient océan","Revenez vers l’est, jusqu’au lac séparé de l’Atlantique par une étroite bande de terre. Les fragments du Breiðamerkurjökull y commencent leur voyage vers la mer.","Les lacs glaciaires occupent les profondes cuvettes révélées par le recul des glaciers."]],
    discoveries:[["Un paysage de moraines","Breiðármörk conserve les crêtes et sédiments laissés par les avancées et reculs glaciaires. Les moraines rendent visibles les anciennes limites de la glace."],["La plaine d’épandage de Skeiðarársandur","L’eau de fonte et les crues soudaines jökulhlaup répandent les sédiments volcaniques et glaciaires vers l’océan, créant une vaste plaine changeante."],["La lagune glaciaire de Jökulsárlón","Jökulsárlón occupe une profonde cuvette creusée par le Breiðamerkurjökull. Quand le glacier recule et vêle, les icebergs traversent la lagune vers l’Atlantique."]]},
  sv:{journal:"Journal",eyebrow:"Fältexpedition 001 · Island",title:"Läs landskapet.<br>Följ vattnet.",intro:"En glaciär har skrivit en berättelse längs Islands sydkust. Följ tre verifierade spår och upptäck hur is, vatten och eld formar vägen mot havet.",level:"● Nyfiken nybörjare",time:"12–15 minuter",region:"Södra Vatnajökull",hint:"Välj den upplysta markören för att undersöka",progress:"Expeditionens framsteg",clue:"Ledtråd",field:"Fältanteckning",manifesto:"Världen är ingen checklista.",manifestoTitle:"Varje landskap lämnar spår.<br>Din uppgift är att se dem.",made:"Upptäckt",knowledge:"Geologikunskap",record:"Spara och fortsätt",explorerJournal:"Upptäckarens journal",notes:"Fältanteckningar från Island",empty:"Din första upptäckt väntar fortfarande i landskapet.",investigate:"Undersök markör {n}",complete:"Expeditionen slutförd",viewSource:"Visa verifierad källa ↗",welcomeEyebrow:"En värld av spår och förundran",welcomeCopy:"Varje berg har en berättelse. Varje flod minns. Börja en upptäckarjournal formad av din nyfikenhet.",begin:"Börja din resa",continueProfile:"Fortsätt som upptäckare",profileEyebrow:"Din upptäckarprofil",profileTitle:"Vad ska din journal kalla dig?",explorerName:"Upptäckarnamn",guideLanguage:"Guidens språk",chooseExpedition:"Välj en expedition",firstExpedition:"Din första expedition",whereFirst:"Var vill du börja leta?",available:"Tillgänglig nu",fieldExpedition:"Fältexpedition 001",fireIce:"Island · En berättelse om eld och is",threeDiscoveries:"3 upptäckter",comingSoon:"Kommer snart",futureExpedition:"Framtida expedition",patagonia:"Patagonien · Där kontinenter slutar",preparing:"Förbereder din expedition",
    clues:[["Åsen som bevarar en gräns","Börja på Breiðármörk, framför en vikande utloppsglaciär. Leta efter ryggar av löst material intill isen. Vilken kraft avsatte dem?","Material som glaciären bär med sig avsätts längs sidorna och iskanten som moräner."],["En slätt skriven av översvämningar","Res västerut till den enorma mörka slätten mellan glaciär och hav. Floderna delar sig och möts över sediment från Vatnajökull.","Återkommande glaciärfloder och smältvatten bygger de vidsträckta slätter som kallas sandur."],["Där is blir hav","Återvänd österut till sjön som skiljs från Atlanten av en smal landremsa. Här börjar delar av Breiðamerkurjökull sin synliga resa mot havet.","Glaciärsjöar bildas i djupa bäcken som blottläggs när utloppsglaciärer drar sig tillbaka."]],
    discoveries:[["Ett landskap av moräner","Breiðármörk bevarar ryggar och sediment från glaciärernas framryckningar och reträtter. Moräner gör tidigare iskanter läsbara i dagens terräng."],["Skeiðarársandurs sandurslätt","Smältvatten och plötsliga jökulhlaup sprider vulkaniskt och glacialt sediment mot havet och skapar en vidsträckt, föränderlig sandurslätt."],["Glaciärlagunen Jökulsárlón","Jökulsárlón ligger i ett djupt bäcken urholkat av Breiðamerkurjökull. När glaciären drar sig tillbaka och kalvar färdas isberg genom lagunen mot Atlanten."]]}
};

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let language=localStorage.getItem("atlas-language")||"en";
let completed=JSON.parse(localStorage.getItem("atlas-journal")||"[]").filter(id=>places.some(place=>place.id===id));
let sideNotes=JSON.parse(localStorage.getItem("atlas-side-notes")||"[]").filter(id=>expeditionCatalog.sideDiscoveries.some(note=>note.id===id));
let profile=JSON.parse(localStorage.getItem("atlas-profile")||"null");
let map,markerElements=[],sideMarkerElements=[];
const text=()=>copy[language];

function initializeMap(){
  if(!window.maplibregl)return;
  map=new maplibregl.Map({container:"real-map",style:{version:8,sources:{osm:{type:"raster",tiles:["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],tileSize:256,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap contributors</a>'}},layers:[{id:"osm",type:"raster",source:"osm",paint:{"raster-saturation":-.65,"raster-contrast":.2,"raster-brightness-max":.72,"raster-brightness-min":.08}}]},center:[-16.7,64.02],zoom:7.4,maxZoom:15,attributionControl:true});
  map.addControl(new maplibregl.NavigationControl({showCompass:true}),"top-right");
  places.forEach((place,index)=>{
    const button=document.createElement("button");button.className="marker";button.dataset.index=index;button.textContent=String(index+1).padStart(2,"0");button.addEventListener("click",()=>{if(index===completed.length)investigate()});
    new maplibregl.Marker({element:button,anchor:"center"}).setLngLat(place.coordinates).addTo(map);markerElements.push(button);
  });
  expeditionCatalog.sideDiscoveries.forEach((note,index)=>{const button=document.createElement('button');button.className='side-marker';button.textContent='✦';button.setAttribute('aria-label',note.locales[language].title);button.addEventListener('click',()=>openFieldNote(index));new maplibregl.Marker({element:button,anchor:'center'}).setLngLat(note.coordinates).addTo(map);sideMarkerElements.push(button)});
  map.on("load",()=>{$(".map").classList.add("map-ready");renderMarkers()});
}

function translate(){document.documentElement.lang=language;$$('[data-t]').forEach(el=>{const value=text()[el.dataset.t];if(value)el.innerHTML=value});$('#language').value=language;updateProfileUI();renderExpeditionHub();render();renderSideNotes();renderDashboard();updateLivingWorld()}
function updateProfileUI(){const name=profile?.name||"Explorer";$('#profile-name').textContent=name;$('#profile-initial').textContent=name.charAt(0).toUpperCase();$('#profile-greeting').textContent=profile?`${name}, your journal begins here.`:"";const returning=$('#skip-onboarding');returning.hidden=!profile;if(profile)returning.textContent=`${text().continueProfile}: ${name}`}
function showStep(name){$$('.onboarding-step').forEach(step=>step.classList.toggle('active',step.dataset.step===name));if(name==='profile'){const nameInput=$('#explorer-name');nameInput.value=profile?.name||'';const selected=profile?.language||language;const radio=$(`input[name="profile-language"][value="${selected}"]`);if(radio)radio.checked=true;$$('input[name="interest"]').forEach(input=>input.checked=(profile?.interests||[]).includes(input.value));setTimeout(()=>nameInput.focus(),50)}if(name==='selection'){updateProfileUI();renderExpeditionHub()}}
function openOnboarding(step='welcome'){const onboarding=$('#onboarding');onboarding.hidden=false;onboarding.classList.remove('departing');document.body.classList.add('onboarding-active');showStep(step)}
function enterExpedition(){const launch=$('#launch-screen');launch.classList.add('active');setTimeout(()=>{const onboarding=$('#onboarding');onboarding.classList.add('departing');document.body.classList.remove('onboarding-active');setTimeout(()=>{onboarding.hidden=true;launch.classList.remove('active');if(map)map.resize();$('#expedition').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});startLivingWorld()},700)},900)}
function renderMarkers(){markerElements.forEach((marker,index)=>{marker.classList.toggle("done",index<completed.length);marker.classList.toggle("active",index===completed.length);marker.disabled=index!==completed.length;marker.setAttribute("aria-label",index<completed.length?`${text().discoveries[index][0]} — complete`:index===completed.length?text().clues[index][0]:`Marker ${index+1} locked`)})}
function render(){const done=completed.length,index=Math.min(done,2),clue=text().clues[index],place=places[index];$('#progress-label').textContent=`${done} / 3`;$('#progress-bar').style.width=`${done/3*100}%`;$('#journal-count').textContent=done;$('#clue-number').textContent=String(index+1).padStart(2,"0");$('#clue-title').textContent=done===3?text().complete:clue[0];$('#clue-copy').textContent=clue[1];$('#field-note').textContent=clue[2];$('#location-name').textContent=place.name;$('#coordinates').textContent=`${place.coordinates[1].toFixed(4)}° N · ${Math.abs(place.coordinates[0]).toFixed(4)}° W`;$('#action-label').textContent=done===3?text().complete:text().investigate.replace("{n}",String(index+1).padStart(2,"0"));$('#investigate').disabled=done===3;renderMarkers();$('#entries').innerHTML=completed.map(id=>{const i=places.findIndex(place=>place.id===id),d=text().discoveries[i],investigation=investigationCopy[language][i];return `<article class="entry"><b>${d[0]}</b><div class="journal-entry-meta"><span>${places[i].name}</span><span>+1 GEOLOGY</span></div><small>${d[1]}</small><em class="journal-evidence">${investigationLabels[language].journal}: ${investigation.lesson}</em></article>`}).join("");$('#empty').hidden=done>0;if(map&&done<3)map.flyTo({center:place.coordinates,zoom:done===1?7:9,essential:false})}
function investigate(){if(completed.length===3)return;openInvestigation(completed.length)}
function openInvestigation(index){const data=investigationCopy[language][index],labels=investigationLabels[language],dialog=$('#investigation-dialog'),form=$('#deduction-form');dialog.dataset.index=index;$('#investigation-title').textContent=data.title;dialog.querySelector('[data-t="investigation"]').textContent=labels.investigation;dialog.querySelector('[data-t="evidenceReviewed"]').textContent=labels.reviewed;dialog.querySelector('[data-t="inspectPrompt"]').textContent=labels.prompt;dialog.querySelector('[data-t="submitDeduction"]').textContent=labels.submit;$('#evidence-count').textContent='0 / 3';$('#deduction-question').textContent=data.question;$('#deduction-feedback').textContent='';$('#deduction-feedback').className='deduction-feedback';form.hidden=true;form.reset();$('#evidence-grid').innerHTML=data.evidence.map((item,i)=>`<button class="evidence-card" type="button" data-evidence="${i}" aria-expanded="false"><span class="evidence-icon">${['⌁','◈','◎'][i]}</span><small>${labels.evidence} ${String(i+1).padStart(2,'0')} · ${item[0]}</small><b>${item[1]}</b><p>${item[2]}</p><span class="sr-only">${labels.review}</span></button>`).join('');$('#deduction-options').innerHTML=data.options.map((option,i)=>`<label class="deduction-option"><input type="radio" name="deduction" value="${i}"><span>${option}</span></label>`).join('');dialog.showModal();dialog.querySelector('.evidence-card').focus()}
function revealDiscovery(index){const discovery=text().discoveries[index];$('#discovery-title').textContent=discovery[0];$('#discovery-copy').textContent=discovery[1];$('#source-link').href=places[index].source;$('#discovery-dialog').showModal()}
function renderDashboard(){const labels=progressionLabels[language],progress=calculateProgression(completed.length),name=profile?.name||'Explorer';$('#dashboard-name').textContent=name;$('#dashboard-initial').textContent=name.charAt(0).toUpperCase();$('#dashboard-rank').textContent=progress.expeditions?labels.fieldExplorer:labels.novice;$('#stat-discoveries').textContent=completed.length;$('#stat-expeditions').textContent=progress.expeditions;$('#label-discoveries').textContent=labels.discoveries;$('#label-expeditions').textContent=labels.expeditions;$('#label-regions').textContent=labels.regions;$('#knowledge-title').textContent=labels.knowledge;$('#knowledge-total').textContent=`${progress.total} ${labels.knowledgePoints}`;$('#geology-label').textContent=labels.geology;$('#cartography-label').textContent=labels.cartography;$('#geology-level').textContent=`${labels.level} ${progress.geology>=3?1:0}`;$('#cartography-level').textContent=`${labels.level} ${progress.cartography>=2?1:0}`;$('#geology-points').textContent=progress.geology;$('#cartography-points').textContent=progress.cartography;$('#geology-bar').style.width=`${progress.geology/3*100}%`;$('#cartography-bar').style.width=`${progress.cartography/2*100}%`;$('#achievement-title').textContent=labels.achievements;$('#achievement-count').textContent=`${progress.achievement?1:0} / 1`;$('#achievement-name').textContent=labels.achievementName;$('#achievement-copy').textContent=labels.achievementCopy;$('#fire-ice-achievement').classList.toggle('locked',!progress.achievement);$('#edit-profile-label').textContent=labels.edit}
function renderMultiRegionProgress(){const regional=['atlas-patagonia-journal','atlas-east-africa-journal'].map(key=>JSON.parse(localStorage.getItem(key)||'[]').length),external=JSON.parse(localStorage.getItem('atlas-completed-expeditions')||'[]'),icelandDone=completed.length>=3,expeditionCount=(icelandDone?1:0)+external.filter(id=>id!=='iceland-fire-ice').length,discoveryCount=completed.length+regional.reduce((sum,count)=>sum+count,0),geology=discoveryCount,cartography=expeditionCount*2,labels=progressionLabels[language];$('#stat-discoveries').textContent=discoveryCount;$('#stat-expeditions').textContent=expeditionCount;$('#label-regions').previousElementSibling.textContent=1+regional.filter(count=>count>0).length;$('#dashboard-rank').textContent=expeditionCount?labels.fieldExplorer:labels.novice;$('#geology-points').textContent=geology;$('#cartography-points').textContent=cartography;$('#geology-level').textContent=`${labels.level} ${Math.floor(geology/3)}`;$('#cartography-level').textContent=`${labels.level} ${expeditionCount}`;$('#geology-bar').style.width=`${Math.min(100,(geology%3||geology?3:0)/3*100)}%`;$('#cartography-bar').style.width=`${expeditionCount?100:0}%`;$('#knowledge-total').textContent=`${geology+cartography} ${labels.knowledgePoints}`}
function openProfileDashboard(){renderDashboard();renderMultiRegionProgress();$('#profile-dialog').showModal()}
function showCompletion(){const labels=progressionLabels[language];$('#completion-eyebrow').textContent=labels.complete;$('#completion-title').textContent=labels.completionTitle;$('#completion-copy').textContent=labels.completionCopy;$('#reward-geology').textContent=labels.geology;$('#reward-cartography').textContent=labels.cartography;$('#reward-achievement').textContent=labels.achievement;$('#view-legacy-label').textContent=labels.viewLegacy;$('#completion-dialog').showModal()}
function renderExpeditionHub(){const interests=profile?.interests||[];$('#expedition-grid').innerHTML=expeditionCatalog.expeditions.map(expedition=>{const local=expedition.locales[language],recommended=expedition.interests.some(interest=>interests.includes(interest));return `<button class="expedition-card ${expedition.id} ${expedition.status!=='available'?'future-card':''}" data-expedition="${expedition.id}" ${expedition.status!=='available'?'disabled':''}><span class="card-status">${recommended?'★ ':''}${local.status}</span><span class="card-landscape" aria-hidden="true"><i></i></span><span class="card-content"><small>${local.type}</small><b>${local.title}</b>${expedition.duration?`<em><span>${expedition.discoveryCount} discoveries</span><span>${expedition.duration}</span></em>`:''}</span></button>`}).join('')}
function openFieldNote(index){const note=expeditionCatalog.sideDiscoveries[index],local=note.locales[language];$('#field-note-dialog').dataset.index=index;$('#field-note-type').textContent=local.type;$('#field-note-title').textContent=local.title;$('#field-note-copy').textContent=local.copy;$('#field-note-source').href=note.source;$('#save-note-label').textContent=sideNotes.includes(note.id)?'Saved to journal':'Save to journal';$('#save-field-note').disabled=sideNotes.includes(note.id);$('#field-note-dialog').showModal()}
function renderSideNotes(){const entries=$('#entries');entries.insertAdjacentHTML('beforeend',sideNotes.map(id=>{const note=expeditionCatalog.sideDiscoveries.find(item=>item.id===id),local=note.locales[language];return `<article class="entry"><b>${local.title}</b><div class="journal-entry-meta"><span>OPTIONAL FIELD NOTE</span><span>${note.interest}</span></div><small>${local.copy}</small></article>`}).join(''));$('#journal-count').textContent=completed.length+sideNotes.length;$('#empty').hidden=completed.length+sideNotes.length>0;sideMarkerElements.forEach((marker,index)=>marker.classList.toggle('saved',sideNotes.includes(expeditionCatalog.sideDiscoveries[index].id)))}

$('#language').addEventListener('change',event=>{language=event.target.value;localStorage.setItem('atlas-language',language);translate()});
$('#begin-onboarding').addEventListener('click',()=>showStep('profile'));
$('#skip-onboarding').addEventListener('click',()=>showStep('selection'));
$('#profile-form').addEventListener('submit',event=>{event.preventDefault();const name=$('#explorer-name').value.trim();if(!name){$('#explorer-name').focus();return}language=$('input[name="profile-language"]:checked').value;const interests=$$('input[name="interest"]:checked').map(input=>input.value);profile={name,language,interests,createdAt:profile?.createdAt||new Date().toISOString()};localStorage.setItem('atlas-profile',JSON.stringify(profile));localStorage.setItem('atlas-language',language);translate();showStep('selection')});
$('#expedition-grid').addEventListener('click',event=>{const card=event.target.closest('[data-expedition]');if(!card)return;if(card.dataset.expedition==='iceland-fire-ice')enterExpedition();else location.href=`region-player.html?expedition=${card.dataset.expedition}`});
$('#profile-button').addEventListener('click',openProfileDashboard);
$('#edit-profile').addEventListener('click',()=>{$('#profile-dialog').close();openOnboarding('profile')});
$('#view-legacy').addEventListener('click',()=>{$('#completion-dialog').close();openProfileDashboard()});
$('#investigate').addEventListener('click',investigate);
$('#evidence-grid').addEventListener('click',event=>{const card=event.target.closest('.evidence-card');if(!card)return;card.classList.add('reviewed');card.setAttribute('aria-expanded','true');const reviewed=$$('#evidence-grid .evidence-card.reviewed').length;$('#evidence-count').textContent=`${reviewed} / 3`;if(reviewed===3){$('#deduction-form').hidden=false;$('#deduction-options input').focus()}});
$('#deduction-form').addEventListener('submit',event=>{event.preventDefault();const dialog=$('#investigation-dialog'),index=Number(dialog.dataset.index),data=investigationCopy[language][index],choice=$('input[name="deduction"]:checked'),feedback=$('#deduction-feedback');if(!choice){feedback.textContent=data.wrong;feedback.className='deduction-feedback';return}if(Number(choice.value)!==data.correct){feedback.textContent=data.wrong;feedback.className='deduction-feedback';return}feedback.textContent=data.right;feedback.className='deduction-feedback correct';$$('#deduction-form input, #deduction-form button').forEach(control=>control.disabled=true);setTimeout(()=>{dialog.close();$$('#deduction-form input, #deduction-form button').forEach(control=>control.disabled=false);revealDiscovery(index)},650)});
$('#record').addEventListener('click',()=>{const wasComplete=completed.length>=3;if(!wasComplete)completed.push(places[completed.length].id);localStorage.setItem('atlas-journal',JSON.stringify(completed));$('#discovery-dialog').close();render();renderDashboard();updateLivingWorld();if(!wasComplete&&completed.length===3)setTimeout(showCompletion,350)});
$('#journal-button').addEventListener('click',()=>$('#journal-dialog').showModal());
$('#save-field-note').addEventListener('click',()=>{const index=Number($('#field-note-dialog').dataset.index),note=expeditionCatalog.sideDiscoveries[index];if(!sideNotes.includes(note.id))sideNotes.push(note.id);localStorage.setItem('atlas-side-notes',JSON.stringify(sideNotes));$('#field-note-dialog').close();render();renderSideNotes()});
$$('.close').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
$$('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()}));
document.body.classList.add('onboarding-active');
initializeLivingWorld();
translate();
openOnboarding('welcome');
try{initializeMap()}catch(error){console.warn('Interactive map unavailable; onboarding remains active.',error)}
