const atlasCopy={en:{eyebrow:'Your living atlas',title:'The world,<br>unfolding.',intro:'Every expedition adds another place to your personal map of Earth.',regions:'Regions discovered',discoveries:'Discoveries',all:'All',available:'Available',completed:'Completed',planned:'Future',futureRegion:'Future region',launch:'Open expedition',preview:'Preview region',complete:'Completed'},fr:{eyebrow:'Votre atlas vivant',title:'Le monde<br>se dévoile.',intro:'Chaque expédition ajoute un lieu à votre carte personnelle de la Terre.',regions:'Régions découvertes',discoveries:'Découvertes',all:'Toutes',available:'Disponibles',completed:'Terminées',planned:'À venir',futureRegion:'Région future',launch:'Ouvrir l’expédition',preview:'Voir la région',complete:'Terminée'},sv:{eyebrow:'Din levande atlas',title:'Världen<br>vecklas ut.',intro:'Varje expedition lägger till en plats på din personliga karta över jorden.',regions:'Upptäckta regioner',discoveries:'Upptäckter',all:'Alla',available:'Tillgängliga',completed:'Slutförda',planned:'Framtid',futureRegion:'Framtida region',launch:'Öppna expedition',preview:'Visa region',complete:'Slutförd'}};
const atlasCoordinates={'iceland-fire-ice':[-19,64.9],'patagonia-continents-end':[-73,-49.8],'east-africa-migrations':[35,-2.2]};
const futureRegions=[{id:'central-asia-silk-roads',status:'planned',region:'Central Asia',atlas:[69,41],locales:{en:{status:'Future region',type:'History expedition',title:'Central Asia · Roads that connected worlds'},fr:{status:'Région future',type:'Expédition historique',title:'Asie centrale · Routes entre les mondes'},sv:{status:'Framtida region',type:'Historisk expedition',title:'Centralasien · Vägar mellan världar'}}}];
let atlasLanguage=localStorage.getItem('atlas-language')||'en',atlasFilter='all',atlasMap,atlasMarkers=[],selectedRegion;
const $a=s=>document.querySelector(s),aText=()=>atlasCopy[atlasLanguage];
function atlasProgress(id){if(id==='iceland-fire-ice'){const n=JSON.parse(localStorage.getItem('atlas-journal')||'[]').length;return{discoveries:n,completed:n>=3}}const storageKeys={'patagonia-continents-end':'atlas-patagonia-journal','east-africa-migrations':'atlas-east-africa-journal'};if(storageKeys[id]){const n=JSON.parse(localStorage.getItem(storageKeys[id])||'[]').length;return{discoveries:n,completed:n>=3}}return{discoveries:0,completed:false}}
function atlasRegions(){return[...expeditionCatalog.expeditions.map(item=>({...item,atlas:atlasCoordinates[item.id]})),...futureRegions]}
function stateFor(region){const progress=atlasProgress(region.id);return region.status==='planned'?'planned':progress.completed?'completed':'available'}
function translateAtlas(){const t=aText();document.documentElement.lang=atlasLanguage;$a('#atlas-language').value=atlasLanguage;$a('#atlas-eyebrow').textContent=t.eyebrow;$a('#atlas-title').innerHTML=t.title;$a('#atlas-intro').textContent=t.intro;$a('#regions-label').textContent=t.regions;$a('#discoveries-label').textContent=t.discoveries;['all','available','completed','planned'].forEach(key=>$a(`[data-filter="${key}"]`).textContent=t[key]);$a('#legend-available').textContent=t.available;$a('#legend-completed').textContent=t.completed;$a('#legend-planned').textContent=t.planned;renderAtlas()}
function renderAtlas(){const regions=atlasRegions(),discovered=regions.filter(r=>atlasProgress(r.id).discoveries>0);$a('#atlas-regions').textContent=discovered.length;$a('#atlas-discoveries').textContent=regions.reduce((sum,r)=>sum+atlasProgress(r.id).discoveries,0);const shown=regions.filter(r=>atlasFilter==='all'||stateFor(r)===atlasFilter);$a('#atlas-list').innerHTML=shown.map(region=>{const local=region.locales[atlasLanguage],state=stateFor(region),progress=atlasProgress(region.id);return`<button class="atlas-item ${state}" data-region="${region.id}"><i></i><span><b>${local.title}</b><small>${local.type}</small></span><em>${state==='completed'?aText().complete:state==='planned'?aText().planned:`${progress.discoveries}/${region.discoveryCount}`}</em></button>`}).join('');$a('#atlas-list').querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>selectRegion(button.dataset.region)));atlasMarkers.forEach(({element,region})=>element.hidden=!shown.some(item=>item.id===region.id))}
function selectRegion(id){const region=atlasRegions().find(item=>item.id===id),local=region.locales[atlasLanguage],state=stateFor(region);selectedRegion=region;$a('#preview-status').textContent=state==='completed'?aText().complete:state==='planned'?aText().futureRegion:aText().available;$a('#preview-title').textContent=local.title;$a('#preview-meta').textContent=region.duration?`${region.discoveryCount} discoveries · ${region.duration}`:local.type;$a('#preview-action').textContent=state==='planned'?aText().preview:aText().launch;$a('#preview-launch').disabled=state==='planned';$a('#region-preview').hidden=false;if(atlasMap)atlasMap.flyTo({center:region.atlas,zoom:state==='planned'?3.2:4,essential:false})}
function initAtlasMap(){if(!window.maplibregl)return;atlasMap=new maplibregl.Map({container:'atlas-map',style:'https://demotiles.maplibre.org/globe.json',center:[-12,25],zoom:1.6,attributionControl:true});atlasMap.addControl(new maplibregl.NavigationControl(),'top-right');atlasMap.on('style.load',()=>atlasMap.setProjection({type:'globe'}));atlasMap.on('load',()=>document.querySelector('.atlas-map-wrap').classList.add('map-ready'));atlasRegions().forEach(region=>{const element=document.createElement('button');element.className=`atlas-marker ${stateFor(region)}`;element.textContent=stateFor(region)==='planned'?'＋':'◎';element.addEventListener('click',()=>selectRegion(region.id));new maplibregl.Marker({element}).setLngLat(region.atlas).addTo(atlasMap);atlasMarkers.push({element,region})})}
$a('#atlas-language').addEventListener('change',e=>{atlasLanguage=e.target.value;localStorage.setItem('atlas-language',atlasLanguage);translateAtlas()});$a('#atlas-filters').addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;atlasFilter=button.dataset.filter;$a('#atlas-filters').querySelectorAll('button').forEach(item=>item.classList.toggle('active',item===button));renderAtlas()});$a('#preview-close').addEventListener('click',()=>$a('#region-preview').hidden=true);$a('#preview-launch').addEventListener('click',()=>{if(!selectedRegion)return;if(selectedRegion.id==='iceland-fire-ice')location.href='index.html';else if(selectedRegion.status==='available')location.href=`region-player.html?expedition=${selectedRegion.id}`});
translateAtlas();try{initAtlasMap()}catch(error){console.warn('Globe unavailable; atlas list remains active.',error)}
