const expeditionCatalog={
  version:1,
  expeditions:[
    {id:'iceland-fire-ice',status:'available',region:'Iceland',duration:'12–15 min',discoveryCount:3,interests:['geology','photography'],locales:{en:{status:'Available now',type:'Field expedition 001',title:'Iceland · A story of fire and ice'},fr:{status:'Disponible',type:'Expédition 001',title:'Islande · Une histoire de feu et de glace'},sv:{status:'Tillgänglig nu',type:'Fältexpedition 001',title:'Island · En berättelse om eld och is'}}},
    {id:'patagonia-continents-end',status:'available',region:'Patagonia',duration:'15–18 min',discoveryCount:3,interests:['history','geology'],locales:{en:{status:'Available now',type:'Field expedition 002',title:'Patagonia · Ice, water, and cloud'},fr:{status:'Disponible',type:'Expédition 002',title:'Patagonie · Glace, eau et nuages'},sv:{status:'Tillgänglig nu',type:'Fältexpedition 002',title:'Patagonien · Is, vatten och moln'}}},
    {id:'east-africa-migrations',status:'available',region:'East Africa',duration:'15–18 min',discoveryCount:3,interests:['wildlife','history','geology'],locales:{en:{status:'Available now',type:'Field expedition 003',title:'East Africa · Paths of life'},fr:{status:'Disponible',type:'Expédition 003',title:'Afrique de l’Est · Chemins de vie'},sv:{status:'Tillgänglig nu',type:'Fältexpedition 003',title:'Östafrika · Livets vägar'}}}
  ],
  sideDiscoveries:[
    {id:'fellsfjara-ice',coordinates:[-16.1778,64.0448],interest:'photography',source:'https://www.vatnajokulsthjodgardur.is/en/areas/jokulsarlon/afangastadur-fellsfjara',locales:{en:{type:'Optional field note · Photography',title:'Ice on black sand',copy:'Glacier ice from Jökulsárlón often reaches Fellsfjara and rests on the black beach. The arrangement changes continually with waves, weather, and new ice.'},fr:{type:'Note facultative · Photographie',title:'La glace sur le sable noir',copy:'La glace de Jökulsárlón atteint souvent Fellsfjara et repose sur la plage noire. La disposition change avec les vagues, la météo et les nouveaux fragments.'},sv:{type:'Valfri fältanteckning · Fotografi',title:'Is på svart sand',copy:'Glaciäris från Jökulsárlón når ofta Fellsfjara och vilar på den svarta stranden. Mönstret förändras med vågor, väder och ny is.'}}},
    {id:'breidamerkur-birds',coordinates:[-16.42,64.035],interest:'wildlife',source:'https://www.vatnajokulsthjodgardur.is/en/nature--history/biome',locales:{en:{type:'Optional field note · Wildlife',title:'Life follows retreating ice',copy:'Breiðamerkursandur is important nesting habitat for birds including great skua and barnacle goose. Newly exposed terrain becomes a place to observe ecosystems forming.'},fr:{type:'Note facultative · Faune',title:'La vie suit le recul de la glace',copy:'Breiðamerkursandur est une zone de nidification importante, notamment pour le grand labbe et la bernache nonnette. Les terres révélées accueillent de nouveaux écosystèmes.'},sv:{type:'Valfri fältanteckning · Djurliv',title:'Livet följer den vikande isen',copy:'Breiðamerkursandur är ett viktigt häckningsområde för bland annat storlabb och vitkindad gås. På den blottlagda marken växer nya ekosystem fram.'}}}
  ]
};
