(function(){
  const copy={en:{eyebrow:'The world we read together',title:'Curiosity<br>connects us.',intro:'Every anonymous contribution moves the shared atlas forward. No names, locations, or personal journal entries are collected.',connecting:'Connecting to the expedition network…',live:'Live community totals',offline:'Community totals are temporarily unavailable. Your progress remains safely on this device.',explorers:'Explorers',discoveries:'Discoveries made',completions:'Expeditions completed',challenge:'Collaborative challenge',challengeTitle:'Map 1,000 discoveries',challengeCopy:'Together, reveal one thousand evidence-led discoveries across the living Earth.',invite:'Invite an explorer',copied:'Invitation link copied.',pulse:'Shared discoveries',pulseTitle:'Where curiosity is moving'},fr:{eyebrow:'Le monde que nous lisons ensemble',title:'La curiosité<br>nous relie.',intro:'Chaque contribution anonyme fait avancer l’atlas partagé. Aucun nom, lieu ou contenu du carnet n’est collecté.',connecting:'Connexion au réseau…',live:'Totaux de la communauté en direct',offline:'Les totaux sont temporairement indisponibles. Votre progression reste sur cet appareil.',explorers:'Explorateurs',discoveries:'Découvertes',completions:'Expéditions terminées',challenge:'Défi collectif',challengeTitle:'Cartographier 1 000 découvertes',challengeCopy:'Révélons ensemble mille découvertes fondées sur des indices.',invite:'Inviter un explorateur',copied:'Lien d’invitation copié.',pulse:'Découvertes partagées',pulseTitle:'Où avance la curiosité'},sv:{eyebrow:'Världen vi läser tillsammans',title:'Nyfikenhet<br>förenar oss.',intro:'Varje anonymt bidrag för den gemensamma atlasen framåt. Inga namn, platser eller journaltexter samlas in.',connecting:'Ansluter till expeditionsnätverket…',live:'Gemenskapens totalsiffror live',offline:'Totalsiffrorna är tillfälligt otillgängliga. Dina framsteg finns tryggt på enheten.',explorers:'Upptäckare',discoveries:'Upptäckter',completions:'Slutförda expeditioner',challenge:'Gemensam utmaning',challengeTitle:'Kartlägg 1 000 upptäckter',challengeCopy:'Tillsammans avslöjar vi tusen evidensbaserade upptäckter.',invite:'Bjud in en upptäckare',copied:'Inbjudningslänken kopierad.',pulse:'Delade upptäckter',pulseTitle:'Vart nyfikenheten rör sig'}};
  const names=['Iceland','Patagonia','East Africa'];let language=localStorage.getItem('atlas-language')||'en',stats;
  const $=selector=>document.querySelector(selector),t=()=>copy[language];
  function translate(){const c=t();document.documentElement.lang=language;$('#community-language').value=language;$('#community-eyebrow').textContent=c.eyebrow;$('#community-title').innerHTML=c.title;$('#community-intro').textContent=c.intro;$('#explorers-label').textContent=c.explorers;$('#community-discoveries-label').textContent=c.discoveries;$('#completions-label').textContent=c.completions;$('#challenge-eyebrow').textContent=c.challenge;$('#challenge-title').textContent=c.challengeTitle;$('#challenge-copy').textContent=c.challengeCopy;$('#invite-label').textContent=c.invite;$('#pulse-eyebrow').textContent=c.pulse;$('#pulse-title').textContent=c.pulseTitle;if(stats)render(stats)}
  function render(data){stats=data;const total=Number(data.discoveries)||0,regions=[Number(data.iceland)||0,Number(data.patagonia)||0,Number(data.east_africa)||0],max=Math.max(1,...regions);$('#community-explorers').textContent=Number(data.explorers||0).toLocaleString();$('#community-discoveries').textContent=total.toLocaleString();$('#community-completions').textContent=Number(data.completions||0).toLocaleString();$('#challenge-progress').textContent=`${Math.min(total,1000).toLocaleString()} / 1,000`;$('#challenge-percent').textContent=`${Math.min(100,Math.floor(total/10))}%`;$('#challenge-bar').style.width=`${Math.min(100,total/10)}%`;$('#region-pulse-list').innerHTML=names.map((name,index)=>`<div class="pulse-row"><div><b>${name}</b><small>${regions[index].toLocaleString()}</small></div><div class="pulse-track"><i style="width:${regions[index]/max*100}%"></i></div></div>`).join('');$('#community-state').textContent=t().live}
  async function load(){try{await window.AtlasCommunity.sync();const data=await window.AtlasCommunity.rpc('community_stats');render(data)}catch{$('#community-state').textContent=t().offline}}
  $('#community-language').addEventListener('change',event=>{language=event.target.value;localStorage.setItem('atlas-language',language);translate()});$('#invite-explorer').addEventListener('click',async()=>{const url='https://atlas.nuhar.se/community.html';try{if(navigator.share)await navigator.share({title:'Atlas Beyond community challenge',url});else await navigator.clipboard.writeText(url);$('#invite-status').textContent=t().copied}catch{}});translate();load();
}());
