const investigationLabels={
  en:{investigation:"Field investigation",reviewed:"Evidence reviewed",prompt:"Inspect every piece of evidence before drawing your conclusion.",submit:"Submit deduction",evidence:"Evidence",review:"Select to examine",journal:"Deduction"},
  fr:{investigation:"Enquête de terrain",reviewed:"Indices examinés",prompt:"Examinez chaque indice avant de tirer votre conclusion.",submit:"Soumettre la déduction",evidence:"Indice",review:"Sélectionnez pour examiner",journal:"Déduction"},
  sv:{investigation:"Fältundersökning",reviewed:"Granskade spår",prompt:"Undersök alla spår innan du drar din slutsats.",submit:"Skicka slutsats",evidence:"Spår",review:"Välj för att undersöka",journal:"Slutsats"}
};

const investigationCopy={
  en:[
    {title:"Read the glacier's former edge",evidence:[["Shape","Curved ridge","The ridge runs across the foreland rather than downhill."],["Material","Mixed stones","Fine sediment and large, scratched rocks lie together without sorting."],["Position","Beyond today's ice","The feature stands away from the glacier's present margin."]],question:"Which explanation best fits all three observations?",options:["A river sorted the stones into a raised bank.","A glacier carried the debris and deposited it at a former margin.","People constructed the ridge as an old road."],correct:1,wrong:"Look again at the unsorted material and its position relative to today's ice.",right:"The evidence supports a moraine: debris deposited at a former glacier margin.",lesson:"Shape + unsorted debris + position reveal an earlier ice margin."},
    {title:"Interpret a restless plain",evidence:[["Pattern","Braided channels","Many shallow channels repeatedly divide and reconnect."],["Surface","Dark sediment","Broad deposits contain volcanic sand, gravel, and glacial material."],["History","Sudden high water","Powerful jökulhlaup floods have crossed this route from beneath Vatnajökull."]],question:"What process best explains this broad, shifting plain?",options:["Repeated meltwater and glacial floods spread sediment toward the sea.","Ocean tides built the entire plain from beach sand.","Wind alone carved channels into an old lava field."],correct:0,wrong:"Combine the braided channels with the evidence of sudden water and transported sediment.",right:"The evidence identifies a sandur—an outwash plain built by glacial water and floods.",lesson:"Braided water + sediment + flood history identify a glacial outwash plain."},
    {title:"Trace the ice to the Atlantic",evidence:[["Basin","A deep trough","The glacier excavated a basin extending far below the surrounding landscape."],["Motion","Calving front","Ice breaks from Breiðamerkurjökull and floats across the lake."],["Outlet","A short river","Lagoon water and ice fragments pass beneath Route 1 toward the ocean."]],question:"Why does this lagoon exist and continue to change?",options:["A volcanic crater filled directly with seawater.","A dam created a permanent reservoir for the nearby road.","A retreating glacier exposed a deep basin where calved ice now travels seaward."],correct:2,wrong:"Follow the sequence from the carved basin, to calving ice, to the ocean outlet.",right:"The observations connect glacial erosion, retreat, calving, and the journey to the sea.",lesson:"A carved basin + retreat + calving explain the living glacial lagoon."}
  ],
  fr:[
    {title:"Lire l’ancienne limite du glacier",evidence:[["Forme","Crête incurvée","La crête traverse l’avant-pays au lieu de descendre la pente."],["Matériaux","Pierres mélangées","Sédiments fins et gros rochers rayés reposent ensemble sans tri."],["Position","Au-delà de la glace actuelle","La formation est éloignée de la marge actuelle du glacier."]],question:"Quelle explication correspond le mieux aux trois observations ?",options:["Une rivière a trié les pierres en une rive surélevée.","Un glacier a transporté les débris et les a déposés sur une ancienne marge.","Des habitants ont construit la crête comme route."],correct:1,wrong:"Regardez encore les matériaux non triés et leur position par rapport à la glace actuelle.",right:"Les indices révèlent une moraine : des débris déposés sur une ancienne marge glaciaire.",lesson:"Forme + débris non triés + position révèlent une ancienne limite de glace."},
    {title:"Interpréter une plaine instable",evidence:[["Motif","Chenaux tressés","De nombreux chenaux peu profonds se divisent et se rejoignent."],["Surface","Sédiments sombres","Les dépôts contiennent sable volcanique, gravier et matériaux glaciaires."],["Histoire","Crues soudaines","De puissants jökulhlaup ont traversé cette route depuis le Vatnajökull."]],question:"Quel processus explique le mieux cette vaste plaine changeante ?",options:["L’eau de fonte et les crues glaciaires ont répandu les sédiments vers la mer.","Les marées ont construit toute la plaine avec du sable de plage.","Le vent seul a creusé les chenaux dans une ancienne coulée de lave."],correct:0,wrong:"Reliez les chenaux tressés, l’eau soudaine et les sédiments transportés.",right:"Les indices identifient un sandur, une plaine d’épandage créée par les eaux glaciaires.",lesson:"Eaux tressées + sédiments + crues identifient une plaine glaciaire."},
    {title:"Suivre la glace vers l’Atlantique",evidence:[["Bassin","Profonde cuvette","Le glacier a creusé une cuvette bien sous le paysage environnant."],["Mouvement","Front de vêlage","La glace se détache du Breiðamerkurjökull et flotte sur le lac."],["Sortie","Courte rivière","L’eau et les fragments passent sous la Route 1 vers l’océan."]],question:"Pourquoi cette lagune existe-t-elle et continue-t-elle à changer ?",options:["Un cratère volcanique s’est rempli directement d’eau de mer.","Un barrage a créé un réservoir permanent pour la route.","Le retrait du glacier a révélé une profonde cuvette où la glace vêlée voyage vers la mer."],correct:2,wrong:"Suivez la séquence : cuvette creusée, vêlage, puis sortie vers l’océan.",right:"Les observations relient érosion glaciaire, recul, vêlage et voyage vers la mer.",lesson:"Cuvette creusée + recul + vêlage expliquent cette lagune vivante."}
  ],
  sv:[
    {title:"Läs glaciärens tidigare kant",evidence:[["Form","Böjd rygg","Ryggen korsar glaciärförlandet i stället för att följa sluttningen."],["Material","Blandade stenar","Fint sediment och stora repade block ligger osorterade tillsammans."],["Läge","Bortom dagens is","Formation ligger på avstånd från glaciärens nuvarande kant."]],question:"Vilken förklaring passar bäst med alla tre observationerna?",options:["En flod sorterade stenarna till en upphöjd bank.","En glaciär bar materialet och avsatte det vid en tidigare iskant.","Människor byggde ryggen som en gammal väg."],correct:1,wrong:"Titta igen på det osorterade materialet och läget i förhållande till dagens is.",right:"Spåren visar en morän: material avsatt vid en tidigare glaciärkant.",lesson:"Form + osorterat material + läge avslöjar en tidigare iskant."},
    {title:"Tolka en rastlös slätt",evidence:[["Mönster","Flätade flodfåror","Många grunda fåror delar sig och möts upprepade gånger."],["Yta","Mörkt sediment","Breda avlagringar innehåller vulkanisk sand, grus och glacialt material."],["Historia","Plötsligt högvatten","Kraftiga jökulhlaup har korsat området från Vatnajökull."]],question:"Vilken process förklarar bäst den breda, föränderliga slätten?",options:["Smältvatten och glaciärfloder spred sediment mot havet.","Tidvatten byggde hela slätten av strandsand.","Enbart vind skar fårorna i ett gammalt lavafält."],correct:0,wrong:"Koppla ihop de flätade fårorna med plötsligt vatten och transporterat sediment.",right:"Spåren identifierar en sandur, en slätt byggd av glacialt vatten och översvämningar.",lesson:"Flätat vatten + sediment + översvämningar identifierar en glacial sandurslätt."},
    {title:"Följ isen till Atlanten",evidence:[["Bäcken","En djup sänka","Glaciären gröpte ur ett bäcken långt under det omgivande landskapet."],["Rörelse","Kalvande front","Is bryts från Breiðamerkurjökull och flyter över sjön."],["Utlopp","En kort flod","Vatten och is passerar under väg 1 mot havet."]],question:"Varför finns lagunen och varför fortsätter den att förändras?",options:["En vulkankrater fylldes direkt med havsvatten.","En damm skapade en permanent reservoar för vägen.","En vikande glaciär blottlade ett djupt bäcken där kalvad is nu färdas mot havet."],correct:2,wrong:"Följ kedjan från det urgröpta bäckenet via kalvande is till havets utlopp.",right:"Observationerna binder samman glacial erosion, reträtt, kalvning och resan mot havet.",lesson:"Urgröpt bäcken + reträtt + kalvning förklarar den levande glaciärlagunen."}
  ]
};
