(function(){
  const copy={en:{title:'Expedition passport',stamps:'stamps',share:'Share explorer passport',copied:'Passport link copied.',shared:'Passport shared.',failed:'Copy this passport link:',locked:'Not yet earned'},fr:{title:'Passeport d’expédition',stamps:'tampons',share:'Partager le passeport',copied:'Lien du passeport copié.',shared:'Passeport partagé.',failed:'Copiez ce lien :',locked:'Pas encore obtenu'},sv:{title:'Expeditionspass',stamps:'stämplar',share:'Dela upptäckarpass',copied:'Passlänken har kopierats.',shared:'Passet har delats.',failed:'Kopiera denna länk:',locked:'Inte intjänad'}};
  const expeditions=[['Iceland','atlas-journal'],['Patagonia','atlas-patagonia-journal'],['East Africa','atlas-east-africa-journal'],['Central Asia','atlas-central-asia-journal']];
  const read=key=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};
  function snapshot(){const profile=read('atlas-profile'),counts=expeditions.map(([,key])=>read(key).length);return{v:1,n:String(profile.name||'Explorer').slice(0,40),l:['en','fr','sv'].includes(profile.language)?profile.language:'en',d:counts.map(value=>Math.max(0,Math.min(3,value)))}}
  function encode(value){const bytes=new TextEncoder().encode(JSON.stringify(value));let binary='';bytes.forEach(byte=>binary+=String.fromCharCode(byte));return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
  function render(){const data=snapshot(),t=copy[data.l],earned=data.d.filter(value=>value>=3).length;document.querySelector('#passport-title').textContent=t.title;document.querySelector('#passport-stamp-count').textContent=`${earned} / ${expeditions.length} ${t.stamps}`;document.querySelector('#share-passport-label').textContent=t.share;document.querySelector('#passport-stamps').innerHTML=expeditions.map(([name],index)=>`<article class="passport-stamp ${data.d[index]>=3?'earned':''}"><b>${name}</b><small>${data.d[index]>=3?'Expedition '+String(index+1).padStart(3,'0'):t.locked}</small></article>`).join('')}
  async function share(){const data=snapshot(),t=copy[data.l],url=new URL('passport.html',location.href);url.hash=`p=${encode(data)}`;const status=document.querySelector('#passport-status');try{if(navigator.share){await navigator.share({title:`${data.n} · Atlas Beyond`,url:url.href});status.textContent=t.shared}else{await navigator.clipboard.writeText(url.href);status.textContent=t.copied}}catch(error){if(error.name!=='AbortError'){status.textContent=`${t.failed} ${url.href}`}}}
  document.querySelector('#profile-button').addEventListener('click',render);
  document.querySelector('#view-legacy').addEventListener('click',render);
  document.querySelector('#share-passport').addEventListener('click',share);
}());
