(function(){
  const copy={en:{rank:'Explorer passport',subtitle:'A record of curiosity across the living Earth.',discoveries:'Discoveries',expeditions:'Expeditions',regions:'Regions visited',home:'Begin your own journey →',locked:'Not yet earned'},fr:{rank:'Passeport d’exploration',subtitle:'Une trace de curiosité à travers la Terre vivante.',discoveries:'Découvertes',expeditions:'Expéditions',regions:'Régions visitées',home:'Commencez votre voyage →',locked:'Pas encore obtenu'},sv:{rank:'Upptäckarpass',subtitle:'Ett minne av nyfikenhet över den levande jorden.',discoveries:'Upptäckter',expeditions:'Expeditioner',regions:'Besökta regioner',home:'Börja din egen resa →',locked:'Inte intjänad'}};
  const names=['Iceland','Patagonia','East Africa','Central Asia'];
  function decode(value){const base=value.replace(/-/g,'+').replace(/_/g,'/');const binary=atob(base);const bytes=Uint8Array.from(binary,char=>char.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
  try{
    const token=new URLSearchParams(location.hash.slice(1)).get('p'),data=decode(token||'');
    if(data.v!==1||typeof data.n!=='string'||!['en','fr','sv'].includes(data.l)||!Array.isArray(data.d)||(data.d.length!==3&&data.d.length!==4))throw new Error('Invalid');
    while(data.d.length<4)data.d.push(0);
    data.d=data.d.map(value=>Math.max(0,Math.min(3,Number(value)||0)));
    const t=copy[data.l],earned=data.d.filter(value=>value>=3).length,discoveries=data.d.reduce((sum,value)=>sum+value,0);
    document.documentElement.lang=data.l;document.title=`${data.n.slice(0,40)} · Atlas Beyond`;document.querySelector('#public-rank').textContent=t.rank;document.querySelector('#public-name').textContent=data.n.slice(0,40)||'Explorer';document.querySelector('#public-initial').textContent=(data.n.trim()[0]||'E').toUpperCase();document.querySelector('#public-subtitle').textContent=t.subtitle;document.querySelector('#public-discoveries').textContent=discoveries;document.querySelector('#public-expeditions').textContent=earned;document.querySelector('#public-regions').textContent=data.d.filter(Boolean).length;document.querySelector('#public-discoveries-label').textContent=t.discoveries;document.querySelector('#public-expeditions-label').textContent=t.expeditions;document.querySelector('#public-regions-label').textContent=t.regions;document.querySelector('#public-home').textContent=t.home;document.querySelector('#public-stamps').innerHTML=names.map((name,index)=>`<article class="passport-stamp ${data.d[index]>=3?'earned':''}"><b>${name}</b><small>${data.d[index]>=3?'Expedition '+String(index+1).padStart(3,'0'):t.locked}</small></article>`).join('');document.querySelector('#passport-content').hidden=false;
  }catch{document.querySelector('#passport-invalid').hidden=false}
}());
