const regionExpeditions={
  'patagonia-continents-end':{
    id:'patagonia-continents-end',region:'Patagonia',center:[-73.0,-49.9],zoom:6.4,storageKey:'atlas-patagonia-journal',
    locales:{
      en:{back:'← Expedition hub',eyebrow:'Field expedition 002 · Patagonia',title:'Ice, water,<br>and cloud.',intro:'Across Los Glaciares National Park, ice can dam a lake, sediment can reveal hidden flow, and a mountain can appear to smoke.',progress:'Expedition progress',investigate:'Investigate evidence',journal:'Field journal',complete:'Patagonia expedition complete',source:'View verified source ↗',record:'Record and continue',evidence:'Evidence',submit:'Submit deduction',wrong:'Compare all three observations before choosing.',discoveries:[
        {place:'Perito Moreno Glacier',coordinates:[-73.137,-50.4967],clue:'A moving wall becomes a dam',field:'Watch what happens where the glacier reaches the opposite shore.',evidence:[['Contact','The advancing ice tongue can meet the Península de Magallanes.'],['Barrier','The grounded ice interrupts circulation between Brazo Rico and Lago Argentino.'],['Pressure','Water rises behind the barrier until it can rupture the ice.']],question:'What role is the glacier playing?',options:['A permanent stone dam','A temporary natural ice dam','A floating island'],correct:1,reveal:'Perito Moreno can form a natural ice dam. Rising water pressure eventually causes a dramatic rupture.',source:'https://science.nasa.gov/earth/earth-observatory/perito-moreno-glacier-argentina-78754/'},
        {place:'Brazo Rico · Lago Argentino',coordinates:[-73.05,-50.47],clue:'Two waters, two colours',field:'A barrier can change more than water level; it can change what the water carries.',evidence:[['Source','Mountain water carries fine glacial sediment into the lake.'],['Separation','The ice dam prevents normal circulation between two bodies of water.'],['Colour','Muddier, milkier water becomes concentrated in Brazo Rico.']],question:'Why can the water on one side look milkier?',options:['The ice barrier concentrates sediment-rich water','Salt enters from the Pacific Ocean','White stones dissolve into the lake'],correct:0,reveal:'Fine glacial sediment remains concentrated when the ice dam restricts circulation, making the water appear milkier.',source:'https://science.nasa.gov/earth/earth-observatory/perito-moreno-glacier-argentina-78754/'},
        {place:'Chaltén · Fitz Roy',coordinates:[-73.043,-49.271],clue:'The mountain that seemed to smoke',field:'A name can preserve an observation even when its first interpretation changes.',evidence:[['Profile','A steep 3,405-metre massif rises sharply above the surrounding terrain.'],['Weather','Clouds frequently gather around and stream from its summit.'],['Name','The Tehuelche name Chaltén is associated with a “smoking mountain.”']],question:'What most likely created the impression of smoke?',options:['A continuously active crater','Summit clouds shaped by mountain weather','Forest fires behind the peak'],correct:1,reveal:'Clouds crowning the massif created the appearance of smoke. The name Chaltén preserves that way of reading the mountain.',source:'https://www.argentina.gob.ar/parquesnacionales/patagonia-austral/parque-nacional-los-glaciares/panoramica'}]},
      fr:{back:'← Centre des expéditions',eyebrow:'Expédition 002 · Patagonie',title:'Glace, eau<br>et nuages.',intro:'Dans le parc national Los Glaciares, la glace peut barrer un lac, les sédiments révéler les courants et une montagne sembler fumer.',progress:'Progression',investigate:'Examiner les indices',journal:'Carnet de terrain',complete:'Expédition en Patagonie terminée',source:'Voir la source ↗',record:'Noter et continuer',evidence:'Indice',submit:'Soumettre la déduction',wrong:'Comparez les trois observations.',discoveries:[
        {place:'Glacier Perito Moreno',coordinates:[-73.137,-50.4967],clue:'Un mur mobile devient un barrage',field:'Observez le glacier lorsqu’il atteint la rive opposée.',evidence:[['Contact','La langue de glace peut toucher la péninsule de Magallanes.'],['Barrière','La glace ancrée interrompt la circulation entre Brazo Rico et Lago Argentino.'],['Pression','L’eau monte derrière la barrière jusqu’à rompre la glace.']],question:'Quel rôle joue le glacier ?',options:['Un barrage permanent en pierre','Un barrage naturel temporaire de glace','Une île flottante'],correct:1,reveal:'Perito Moreno peut former un barrage naturel de glace, rompu ensuite par la pression de l’eau.',source:'https://science.nasa.gov/earth/earth-observatory/perito-moreno-glacier-argentina-78754/'},
        {place:'Brazo Rico · Lago Argentino',coordinates:[-73.05,-50.47],clue:'Deux eaux, deux couleurs',field:'Une barrière modifie aussi ce que transporte l’eau.',evidence:[['Source','L’eau des montagnes transporte de fins sédiments glaciaires.'],['Séparation','Le barrage de glace limite la circulation entre les eaux.'],['Couleur','L’eau plus laiteuse se concentre dans Brazo Rico.']],question:'Pourquoi un côté paraît-il plus laiteux ?',options:['La barrière concentre l’eau riche en sédiments','Le sel arrive du Pacifique','Des pierres blanches se dissolvent'],correct:0,reveal:'Les sédiments glaciaires se concentrent lorsque le barrage limite la circulation.',source:'https://science.nasa.gov/earth/earth-observatory/perito-moreno-glacier-argentina-78754/'},
        {place:'Chaltén · Fitz Roy',coordinates:[-73.043,-49.271],clue:'La montagne qui semblait fumer',field:'Un nom peut conserver une observation ancienne.',evidence:[['Profil','Un massif de 3 405 mètres domine brutalement le terrain.'],['Météo','Les nuages entourent souvent son sommet.'],['Nom','Le nom tehuelche Chaltén évoque une « montagne fumante ».']],question:'Qu’est-ce qui donnait l’impression de fumée ?',options:['Un cratère toujours actif','Les nuages façonnés par le relief','Des feux de forêt'],correct:1,reveal:'Les nuages autour du sommet créaient l’apparence de fumée, préservée par le nom Chaltén.',source:'https://www.argentina.gob.ar/parquesnacionales/patagonia-austral/parque-nacional-los-glaciares/panoramica'}]},
      sv:{back:'← Expeditionsnav',eyebrow:'Fältexpedition 002 · Patagonien',title:'Is, vatten<br>och moln.',intro:'I Los Glaciares kan is dämma en sjö, sediment avslöja flöden och ett berg se ut att ryka.',progress:'Expeditionens framsteg',investigate:'Undersök spåren',journal:'Fältjournal',complete:'Patagonienexpeditionen slutförd',source:'Visa källa ↗',record:'Spara och fortsätt',evidence:'Spår',submit:'Skicka slutsats',wrong:'Jämför alla tre observationer.',discoveries:[
        {place:'Perito Moreno-glaciären',coordinates:[-73.137,-50.4967],clue:'En rörlig vägg blir en damm',field:'Se vad som händer när glaciären når motsatta stranden.',evidence:[['Kontakt','Istungan kan nå Magallaneshalvön.'],['Barriär','Den bottenfasta isen stoppar cirkulation mellan Brazo Rico och Lago Argentino.'],['Tryck','Vattnet stiger tills isen brister.']],question:'Vilken roll spelar glaciären?',options:['En permanent stendamm','En tillfällig naturlig isdamm','En flytande ö'],correct:1,reveal:'Perito Moreno kan bilda en naturlig isdamm som till slut brister av vattentrycket.',source:'https://science.nasa.gov/earth/earth-observatory/perito-moreno-glacier-argentina-78754/'},
        {place:'Brazo Rico · Lago Argentino',coordinates:[-73.05,-50.47],clue:'Två vatten, två färger',field:'En barriär förändrar också vad vattnet bär.',evidence:[['Källa','Bäckar för med sig fint glaciärsediment.'],['Separation','Isdammen begränsar cirkulation mellan vattnen.'],['Färg','Grumligare, mjölkigare vatten samlas i Brazo Rico.']],question:'Varför kan ena sidan se mjölkigare ut?',options:['Barriären koncentrerar sedimentrikt vatten','Salt kommer från Stilla havet','Vita stenar löses upp'],correct:0,reveal:'Fint glaciärsediment koncentreras när isdammen begränsar cirkulationen.',source:'https://science.nasa.gov/earth/earth-observatory/perito-moreno-glacier-argentina-78754/'},
        {place:'Chaltén · Fitz Roy',coordinates:[-73.043,-49.271],clue:'Berget som tycktes ryka',field:'Ett namn kan bevara en gammal observation.',evidence:[['Profil','Ett 3 405 meter högt massiv reser sig brant.'],['Väder','Moln samlas ofta runt toppen.'],['Namn','Det tehuelchiska namnet Chaltén förknippas med ett ”rykande berg”.']],question:'Vad skapade troligen intrycket av rök?',options:['En ständigt aktiv krater','Toppmoln formade av bergsvädret','Skogsbränder bakom toppen'],correct:1,reveal:'Moln kring toppen skapade intrycket av rök. Namnet Chaltén bevarar den läsningen.',source:'https://www.argentina.gob.ar/parquesnacionales/patagonia-austral/parque-nacional-los-glaciares/panoramica'}]}
    }
  }
};
