const progressionLabels={
  en:{novice:"Novice explorer",fieldExplorer:"Field explorer",discoveries:"Discoveries",expeditions:"Expeditions",regions:"Regions visited",knowledge:"Knowledge paths",knowledgePoints:"knowledge",geology:"Geology",cartography:"Cartography",level:"Level",achievements:"Achievements",achievementName:"Reader of Fire & Ice",achievementCopy:"Complete the Iceland field expedition.",edit:"Edit explorer profile",complete:"Expedition complete",completionTitle:"You read the story of fire and ice.",completionCopy:"Three landscapes, one connected system. Your journal now preserves the evidence.",achievement:"Achievement",viewLegacy:"View explorer legacy"},
  fr:{novice:"Explorateur novice",fieldExplorer:"Explorateur de terrain",discoveries:"Découvertes",expeditions:"Expéditions",regions:"Régions visitées",knowledge:"Domaines de connaissance",knowledgePoints:"connaissances",geology:"Géologie",cartography:"Cartographie",level:"Niveau",achievements:"Accomplissements",achievementName:"Lecteur du feu et de la glace",achievementCopy:"Terminez l’expédition de terrain en Islande.",edit:"Modifier le profil",complete:"Expédition terminée",completionTitle:"Vous avez lu l’histoire du feu et de la glace.",completionCopy:"Trois paysages, un seul système. Votre carnet conserve maintenant les indices.",achievement:"Accomplissement",viewLegacy:"Voir votre héritage"},
  sv:{novice:"Nybörjarupptäckare",fieldExplorer:"Fältupptäckare",discoveries:"Upptäckter",expeditions:"Expeditioner",regions:"Besökta regioner",knowledge:"Kunskapsområden",knowledgePoints:"kunskap",geology:"Geologi",cartography:"Kartografi",level:"Nivå",achievements:"Prestationer",achievementName:"Läsare av eld och is",achievementCopy:"Slutför fältexpeditionen på Island.",edit:"Redigera upptäckarprofil",complete:"Expeditionen slutförd",completionTitle:"Du läste berättelsen om eld och is.",completionCopy:"Tre landskap, ett sammanhängande system. Din journal bevarar nu spåren.",achievement:"Prestation",viewLegacy:"Visa ditt arv"}
};

function calculateProgression(discoveryCount){
  const expeditionComplete=discoveryCount>=3;
  return {geology:Math.min(discoveryCount,3),cartography:expeditionComplete?2:0,expeditions:expeditionComplete?1:0,regions:1,achievement:expeditionComplete,total:Math.min(discoveryCount,3)+(expeditionComplete?2:0)};
}
