const expeditionId=new URLSearchParams(location.search).get('expedition')||'patagonia-continents-end';
const expedition=regionExpeditions[expeditionId];
if(!expedition)location.href='index.html';
document.body.dataset.expedition=expeditionId;
let regionLanguage=localStorage.getItem('atlas-language')||'en';
let regionProgress=JSON.parse(localStorage.getItem(expedition.storageKey)||'[]');
let regionMap,regionMarkers=[];
const $r=s=>document.querySelector(s),rText=()=>expedition.locales[regionLanguage];

function initRegionMap(){if(!window.maplibregl)return;regionMap=new maplibregl.Map({container:'region-map',style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>'}},layers:[{id:'osm',type:'raster',source:'osm',paint:{'raster-saturation':-.55,'raster-contrast':.15,'raster-brightness-max':.78}}]},center:expedition.center,zoom:expedition.zoom});regionMap.addControl(new maplibregl.NavigationControl(),'top-right');rText().discoveries.forEach((discovery,index)=>{const button=document.createElement('button');button.className='region-marker';button.textContent=String(index+1).padStart(2,'0');button.addEventListener('click',()=>{if(index===regionProgress.length)openRegionInvestigation(index)});new maplibregl.Marker({element:button}).setLngLat(discovery.coordinates).addTo(regionMap);regionMarkers.push(button)});renderRegion()}
function translateRegion(){const t=rText();document.documentElement.lang=regionLanguage;document.title=`${expedition.region} · Atlas Beyond`;$r('#region-language').value=regionLanguage;$r('#back-link').textContent=t.back;$r('#region-eyebrow').textContent=t.eyebrow;$r('#region-title').innerHTML=t.title;$r('#region-intro').textContent=t.intro;$r('#region-progress-label').textContent=t.progress;$r('#region-journal-button').firstChild.textContent=`${t.journal} `;$r('#region-journal-region').textContent=expedition.region;renderRegion()}
function renderRegion(){const t=rText(),done=regionProgress.length,index=Math.min(done,2),d=t.discoveries[index],lat=d.coordinates[1],lng=d.coordinates[0];$r('#region-progress').textContent=`${done} / 3`;$r('#region-progress-bar').style.width=`${done/3*100}%`;$r('#region-count').textContent=done;$r('#region-step').textContent=String(index+1).padStart(2,'0');$r('#region-clue').textContent=done===3?t.complete:d.clue;$r('#region-field').textContent=d.field;$r('#region-place').textContent=d.place;$r('#region-coordinates').textContent=`${Math.abs(lat).toFixed(3)}° ${lat<0?'S':'N'} · ${Math.abs(lng).toFixed(3)}° ${lng<0?'W':'E'}`;$r('#region-action').textContent=done===3?t.complete:t.investigate;$r('#region-investigate').disabled=done===3;regionMarkers.forEach((marker,i)=>{marker.classList.toggle('done',i<done);marker.classList.toggle('active',i===done);marker.disabled=i!==done});$r('#region-entries').innerHTML=regionProgress.map((_,i)=>{const item=t.discoveries[i];return `<article class="entry"><b>${item.place}</b><small>${item.reveal}</small></article>`}).join('');if(regionMap&&done<3)regionMap.flyTo({center:d.coordinates,zoom:done===2?8:7,essential:false})}
function openRegionInvestigation(index){const t=rText(),d=t.discoveries[index],dialog=$r('#region-investigation');dialog.dataset.index=index;$r('#region-evidence-label').textContent=t.evidence;$r('#region-investigation-title').textContent=d.clue;$r('#region-evidence').innerHTML=d.evidence.map((e,i)=>`<button type="button" class="evidence-card" aria-expanded="false"><span class="evidence-icon">${['⌁','◈','◎'][i]}</span><small>${e[0]}</small><b>${e[1]}</b></button>`).join('');$r('#region-question').textContent=d.question;$r('#region-options').innerHTML=d.options.map((o,i)=>`<label class="deduction-option"><input type="radio" name="region-answer" value="${i}"><span>${o}</span></label>`).join('');$r('#region-feedback').textContent='';$r('#region-deduction').hidden=true;$r('#region-submit').textContent=t.submit;dialog.showModal()}
function showRegionDiscovery(index){const t=rText(),d=t.discoveries[index];$r('#region-discovery-title').textContent=d.place;$r('#region-discovery-copy').textContent=d.reveal;$r('#region-source').textContent=t.source;$r('#region-source').href=d.source;$r('#region-record').textContent=t.record;$r('#region-discovery').dataset.index=index;$r('#region-discovery').showModal()}
$r('#region-language').addEventListener('change',e=>{regionLanguage=e.target.value;localStorage.setItem('atlas-language',regionLanguage);translateRegion()});
$r('#region-investigate').addEventListener('click',()=>openRegionInvestigation(regionProgress.length));
$r('#region-evidence').addEventListener('click',e=>{const card=e.target.closest('.evidence-card');if(!card)return;card.classList.add('reviewed');card.setAttribute('aria-expanded','true');if(document.querySelectorAll('#region-evidence .reviewed').length===3)$r('#region-deduction').hidden=false});
$r('#region-deduction').addEventListener('submit',e=>{e.preventDefault();const index=Number($r('#region-investigation').dataset.index),d=rText().discoveries[index],choice=document.querySelector('input[name="region-answer"]:checked');if(!choice||Number(choice.value)!==d.correct){$r('#region-feedback').textContent=rText().wrong;return}$r('#region-feedback').textContent=d.reveal;$r('#region-feedback').classList.add('correct');setTimeout(()=>{$r('#region-investigation').close();showRegionDiscovery(index)},500)});
$r('#region-record').addEventListener('click',()=>{const index=Number($r('#region-discovery').dataset.index);if(!regionProgress.includes(index))regionProgress.push(index);localStorage.setItem(expedition.storageKey,JSON.stringify(regionProgress));if(regionProgress.length===3){const complete=JSON.parse(localStorage.getItem('atlas-completed-expeditions')||'[]');if(!complete.includes(expeditionId))complete.push(expeditionId);localStorage.setItem('atlas-completed-expeditions',JSON.stringify(complete))}$r('#region-discovery').close();renderRegion()});
$r('#region-journal-button').addEventListener('click',()=>{$r('#region-journal-title').textContent=rText().journal;$r('#region-journal').showModal()});
document.querySelectorAll('.close').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
translateRegion();try{initRegionMap()}catch(error){console.warn('Map unavailable',error)}
