(function(){
const paths=['geology','ecology','history','navigation','cartography'],icons={geology:'△',ecology:'⌁',history:'◫',navigation:'⌖',cartography:'◇'},copy={en:{title:'Explorer lenses',total:'knowledge',level:'Level',requires:'Requires',unlocked:'Lens available'},fr:{title:'Regards d’explorateur',total:'connaissances',level:'Niveau',requires:'Requiert',unlocked:'Regard disponible'},sv:{title:'Upptäckarlinser',total:'kunskap',level:'Nivå',requires:'Kräver',unlocked:'Lins tillgänglig'}},names={en:{geology:'Geology',ecology:'Ecology',history:'History',navigation:'Navigation',cartography:'Cartography'},fr:{geology:'Géologie',ecology:'Écologie',history:'Histoire',navigation:'Navigation',cartography:'Cartographie'},sv:{geology:'Geologi',ecology:'Ekologi',history:'Historia',navigation:'Navigation',cartography:'Kartografi'}};
const read=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
function snapshot(catalog){const points={geology:read('atlas-journal').length,ecology:0,history:0,navigation:0,cartography:0},saved=new Set(read('atlas-side-notes')),completed=read('atlas-completed-expeditions');for(const note of catalog.sideDiscoveries)if(saved.has(note.id)){const path=note.skillPath||'geology';points[path]=(points[path]||0)+1}points.cartography=(read('atlas-journal').length>=3?1:0)+completed.filter((id,index,list)=>list.indexOf(id)===index&&id!=='iceland-fire-ice').length;return points}
function language(){const value=localStorage.getItem('atlas-language')||'en';return copy[value]?value:'en'}
function unlocked(note,catalog){return (snapshot(catalog)[note.skillPath||'geology']||0)>=(note.unlockLevel||0)}
function requirement(note,catalog){const lang=language(),path=note.skillPath||'geology',points=snapshot(catalog)[path]||0,required=note.unlockLevel||0;return unlocked(note,catalog)?copy[lang].unlocked:`${copy[lang].requires} ${names[lang][path]} ${required} · ${points}/${required}`}
function render(catalog){let section=document.querySelector('#explorer-lenses');if(!section){section=document.createElement('section');section.id='explorer-lenses';section.className='knowledge-section explorer-lenses';document.querySelector('.knowledge-section')?.insertAdjacentElement('afterend',section)}if(!section)return;const lang=language(),t=copy[lang],points=snapshot(catalog),total=Object.values(points).reduce((sum,value)=>sum+value,0);section.innerHTML=`<div class="section-heading"><h3>${t.title}</h3><small>${total} ${t.total}</small></div><div class="lens-grid">${paths.map(path=>`<div class="lens-skill"><span>${icons[path]}</span><div><b>${names[lang][path]}</b><small>${t.level} ${points[path]}</small></div><strong>${points[path]}</strong></div>`).join('')}</div>`}
window.AtlasSkills={snapshot,unlocked,requirement,render};
}());
